spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boardProject?useUnicode=true&charaterEncoding=utf-8
    username: boardProject
    password: boardProject
    driver-class-name: com.mysql.jdbc.Driver
    
  freemarker:
    cache: false
    
  jpa:
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
          
mail:
  host: smtp.gmail.com
  port: 587
  protocol: smtp
  encoding: UTF-8