spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boardProject?useUnicode=true&charaterEncoding=utf-8
    username: boardProject
    password: boardProject
    driver-class-name: com.mysql.jdbc.Driver
    
---

spring: 
  freemarker:
    cache: false
    
---

spring:
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

---

spring:
  view:
    prefix: /
    suffix: .ftl