spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boardProject?useUnicode=true&charaterEncoding=utf-8
    username: boardProject
    password: boardProject
    driver-class-name: com.mysql.jdbc.Driver
    
  freemarker:
    cache: false
    
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true